### ISSUE TITLE
Crashes in Ghost 4

### ISSUE THREAD

**Issue by adikari** [eexit/ghost-storage-cloudinary#123]
I am trying to use this in Ghost 4 and seems like when I upload the image, it crashes the entire ghost instance.

I am running this in the dockerized version. I can't really see the logs to figure out what the actual problem is. 

Would be cool if this worked with Ghost 4.

**Comment by charlie-NJ** [comment]
I too am getting an error when I make a changes to the config file.
Here is my error,
`✔ Checking system Node.js version - found v14.17.0
ℹ Ensuring user is not logged in as ghost user [skipped]
ℹ Checking if logged in user is directory owner [skipped]
✔ Checking current folder permissions
✔ Validating config
✔ Checking content folder ownership
✔ Checking memory availability
✔ Checking binary dependencies
✖ Starting Ghost: ecto-1-paulapplegate-com
A SystemError occurred.

Message: The content folder is not owned by the current user.
Ensure the content folder has correct permissions and try again.

Debug Information:
    OS: Ubuntu, v20.04.2 LTS
    Node Version: v14.17.0
    Ghost Version: 4.4.0
    Ghost-CLI Version: 1.17.1
    Environment: production
    Command: 'ghost start'

Try running ghost doctor to check your system for known issues.

You can always refer to https://ghost.org/docs/ghost-cli/ for troubleshooting.
`

After restoring the original file it works again. I used the sample file in the README, [here](https://github.com/eexit/ghost-storage-cloudinary/blob/master/configuration.json.dist)

The node module that was moved I don't think is the problem because I ran ghost start after moving it to the storage directory. Any ideas?

**Comment by eexit** [comment]
Hello,

Could this be related [to this](https://github.com/eexit/ghost-storage-cloudinary/pull/129)?

Thanks.

**Comment by eexit** [comment]
🚀 https://github.com/eexit/ghost-storage-cloudinary/releases/tag/v2.2.0
