### ISSUE TITLE
Image appears duplicated on upload

### ISSUE THREAD

**Issue by carloscuesta** [eexit/ghost-storage-cloudinary#50]
Hello @eexit!

I found out a little problem while uploading images using `ghost-cloudinary-storage`. Every time I upload a new image from Ghost, it appears uploaded twice on the Cloudinary dashboard.

I've been looking at the Console to see if the request was made twice but seems that is firing only once 🤔 

<img width="1441" alt="Screenshot 2019-09-11 at 22 44 37" src="https://user-images.githubusercontent.com/7629661/64733847-c89f6780-d4e5-11e9-8165-b0c001db12d7.png">

<img width="533" alt="Screenshot 2019-09-11 at 22 44 50" src="https://user-images.githubusercontent.com/7629661/64733857-cb01c180-d4e5-11e9-914b-1e579c0a7664.png">

This is my configuration file: 

```
"storage": {
    "active": "ghost-storage-cloudinary",
    "ghost-storage-cloudinary": {
      "cloud_name": "removed",
      "api_key": "removed",
      "api_secret": "removed",
      "configuration": {
        "image": {
          "secure": true
        },
        "file": {}
      }
    }
  },
```

Thanks!

**Comment by eexit** [comment]
Hi @carloscuesta,

Thanks for reporting this. Indeed, Ghost now provides native image optimization and thus saves the original images with a `_o` [prefix](https://github.com/TryGhost/Ghost/blob/master/core/server/web/shared/middlewares/image/handle-image-sizes.js#L65).

In order to disable this, you need to set false [here](https://github.com/TryGhost/Ghost/blob/master/core/server/config/defaults.json#L97).

I'm gonna update the sample config file.

**Comment by carloscuesta** [comment]
Oh! My bad for not searching a little bit more about this, thanks for the quick response! 🙏
